### ISSUE TITLE
Problem with JSX highlighting

### ISSUE THREAD

**Issue by Grawl** [logux/logux.io#15]
When I see [Client Example](https://logux.io/#client-example), there is a problem with JSX highlighting:

<img width="833" alt="изображение" src="https://user-images.githubusercontent.com/846774/71870426-9931fc00-3161-11ea-9533-fa81f40b4adc.png">

With `github` theme in `9.17.1` version it should look like this:

<img width="806" alt="изображение" src="https://user-images.githubusercontent.com/846774/71870534-03e33780-3162-11ea-9e1b-8fb90b68a6a1.png">

I created a [Codepen sandbox](https://codepen.io/Grawl/pen/MWYrRaB) to see how it should work.

I checked out what version of Highlight.js is used in project and it's latest one:

```
➜ cat node_modules/highlight.js/package.json | grep version
  "version": "9.17.1",
```

**Comment by ai** [comment]
Will Prism.js solve the problem?

**Comment by Grawl** [comment]
looks like we're facing https://github.com/highlightjs/highlight.js/issues/931 and this issue is solved in Highlight.js.

Prism can also solve our problem.

**Comment by ai** [comment]
Do you want to try to replace highlighter and get some experience with my fancy build system?

Here we call a highlighter https://github.com/logux/logux.io/blob/master/scripts/steps/read-docs.js#L212-L215

You can test highlighter by calling:

```sh
yarn build
npx ssdeploy run
```

(You can keep `ssdeploy` running in the background and rebuild HTML files by calling `yarn build` again, Docker will load changes into nginx)

**Comment by ai** [comment]
Closing it for now, since I will not have time for it
