### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by tensegrity666** [logux/logux.io#17]
![screenshot](https://user-images.githubusercontent.com/50484733/71917829-0e1d2a00-3192-11ea-9b8a-58af3eb15776.png)

Inactive examples are not available when navigating from the keyboard, as on all button elements, except the selected one, dynamically set "tabindex = -1".

**Comment by ai** [comment]
We did it by a reason. Try move focus to open tab and then press left/right keys.

I am thinking about the whole tabs control as a single control. It is useful to not spending time with tabbing throw long list of tabs.

Does it make sense?

**Comment by tensegrity666** [comment]
> Try move focus to open tab and then press left/right keys.

It works)
