### ISSUE TITLE
Incorrect hover and focus state for title links with code

### ISSUE THREAD

**Issue by hudochenkov** [logux/logux.io#3]
Hover a focus states needs to be adjusted for case, when title has code inside:

<img width="322" alt="Screen Shot 2019-12-06 at 10 42 34" src="https://user-images.githubusercontent.com/654597/70313046-260d3100-1815-11ea-9b55-9dc0cd9ce2bb.png">

https://logux.io/guide/concepts/subscription/#connect

Amazing website!

**Comment by ai** [comment]
Fixed dd5fe20

Thanks for report
