### ISSUE TITLE
How can I run it locally with nginx

### ISSUE THREAD

**Issue by boldevelop** [logux/logux.io#30]
I'm trying to run static server (not uikit.html) locally with nginx, cuz i detect nginx.conf file.

- I included local nginx.conf in main config.
- I ran build.js.

My directories structures:
```
projects/
  logux-*
  logux.io
```
Root nginx config have:
```
# ...
listen       8080;
server_name  localhost;
# ....
location / {
            root   "C:\projects";
            index  index.html index.htm;
}
# ...
```
And `http://localhost:8080/logux.io/ cannot reachable`

Which steps i miss?
I'm on windows 10, but can switch to linux.

Thanks

**Comment by ai** [comment]
There is a simple server `yarn start`.

Running with nginx is complicated. This case is for servers. But if you want to try it you should build and run Docker image by `npx ssdeploy run`.

I will improve docs.

**Comment by ai** [comment]
I added docs https://github.com/logux/logux.io#development
