### ISSUE TITLE
use Pug filters to generate code highlighting output HTML

### ISSUE THREAD

**Issue by Grawl** [logux/logux.io#6]
instead of copying code highlighting output HTML into Pug template, 

https://github.com/logux/logux.io/blob/master/src/uikit.pug#L162

we can use [Pug filters](https://pugjs.org/language/filters.html) like this:

```pug
:md
  ```js
  const { Server } = require('@logux/server')

  function usersReducers (state = { }, action) {
    if (action.type === 'user/name') {
      return { ...state, name: action.name }
    } else {
      return state
    }
  }

  server.auth((userId, token) => {
    // Allow only local users until we will have a proper authentication
    return process.env.NODE_ENV === 'development'
  })
```

to do this, we have to add custom Pug filter and render Markdown using the same way it renders markdown files like [this](https://github.com/logux/docs/blob/master/recipes/authentication.md)

**Comment by ai** [comment]
I created [new open source project](https://github.com/ai/jstransformer-lowlight) to make it happen.

**Comment by ai** [comment]
Fixed 421f651

**Comment by Grawl** [comment]
Parcel has create `:lowlght` filter for Pug automagically?

**Comment by ai** [comment]
Pug does it by looking to `package.json` for all `jstransform-…` packages
